name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Customer Service
      run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/customer-services:latest ./Labs_Sessional/Cafe_Management_System/customer-services
          docker push ${{ secrets.DOCKER_USERNAME }}/customer-services:latest

    - name: Build and Push Inventory Service
      run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/inventory-services:latest ./Labs_Sessional/Cafe_Management_System/inventory-services
          docker push ${{ secrets.DOCKER_USERNAME }}/inventory-services:latest

    - name: Build and Push Menu Service
      run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/menu-services:latest ./Labs_Sessional/Cafe_Management_System/menu-services
          docker push ${{ secrets.DOCKER_USERNAME }}/menu-services:latest

    - name: Build and Push Order Service
      run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/order-services:latest ./Labs_Sessional/Cafe_Management_System/order-services
          docker push ${{ secrets.DOCKER_USERNAME }}/order-services:latest

    - name: Build and Push Menu Service
      run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/payment-services:latest ./Labs_Sessional/Cafe_Management_System/payment-services
          docker push ${{ secrets.DOCKER_USERNAME }}/payment-services:latest
          
    - name: Build and Push Gateway
      run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest ./gateway
          docker push ${{ secrets.DOCKER_USERNAME }}/gateway:latest
